package signal

// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-12-16 19:42:20.033234 +0100 CET m=+0.008293758

type (
	signedChannel struct {
		buffer  Signed
		channel int
	}
)

// Append panics.
func (c signedChannel) Append(s Signed) {
	panic("appending signal to the single channel")
}

// AppendSample panics.
func (c signedChannel) AppendSample(s int64) {
	panic("appending sample to the single channel")
}

// BufferIndex returns sample index in the channel of signal buffer.
func (c signedChannel) BufferIndex(channel int, index int) int {
	return c.channel * index
}

// Channels always returns 1.
func (c signedChannel) Channels() int {
	return 1
}

// Cap returns capacity of the channel.
func (c signedChannel) Cap() int {
	return c.buffer.Capacity()
}

// Capacity returns capacity of the channel.
func (c signedChannel) Capacity() int {
	return c.buffer.Capacity()
}

// Len returns length of the channel.
func (c signedChannel) Len() int {
	return c.buffer.Length()
}

// Length returns length of the channel.
func (c signedChannel) Length() int {
	return c.buffer.Length()
}

// Channel panics.
func (c signedChannel) Channel(channel int) Signed {
	panic("slicing channel of the channel")
}

// Sample returns signal value for provided channel and index.
func (c signedChannel) Sample(index int) int64 {
	return c.buffer.Sample(index * c.channel)
}

// SetSample sets sample value for provided index.
func (c signedChannel) SetSample(index int, s int64) {
	c.buffer.SetSample(c.buffer.BufferIndex(c.channel, index), s)
}

// Free panics.
func (c signedChannel) Free(*PoolAllocator) {
	panic("freeing single channel of the buffer")
}

// Slice slices buffer with respect to channels.
func (c signedChannel) Slice(start, end int) Signed {
	return signedChannel{
		buffer:  c.buffer.Slice(start, end),
		channel: c.channel,
	}
}

func (c signedChannel) BitDepth() BitDepth {
	return c.buffer.BitDepth()
}
