package signal_test

// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-07-25 14:10:01.608818 +0200 CEST m=+0.030829086

import (
	"testing"

	"pipelined.dev/signal"
)

func TestFloat32(t *testing.T) {
	t.Run("float32", func() func(t *testing.T) {
		input := signal.Allocator{
			Channels: 3,
			Capacity: 3,
			Length:   3,
		}.Float32()
		signal.WriteStripedFloat32(
			[][]float32{
				{},
				{1, 2, 3},
				{11, 12, 13, 14},
			},
			input,
		)
		return testOk(
			signal.Allocator{
				Channels: 3,
				Capacity: 2,
			}.Float32().Append(input).Slice(1, 3),
			expected{
				length:   2,
				capacity: 4,
				data: [][]float32{
					{0, 0},
					{2, 3},
					{12, 13},
				},
			},
		)
	}())
}
