// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-05-25 04:38:56.13242 +0200 CEST m=+0.013859144
package signal_test

import (
	"testing"

	"pipelined.dev/signal"
)

func TestInt16(t *testing.T) {
	t.Run("int16", testOk(
		signal.Allocator{
			Channels: 3,
			Capacity: 2,
		}.Int16(signal.BitDepth16).
			Append(signal.WriteStripedInt16(
				[][]int16{
					{},
					{1, 2, 3},
					{11, 12, 13, 14},
				},
				signal.Allocator{
					Channels: 3,
					Capacity: 3,
				}.Int16(signal.BitDepth16)),
			).
			Slice(1, 3),
		expected{
			length:   2,
			capacity: 4,
			data: [][]int16{
				{0, 0},
				{2, 3},
				{12, 13},
			},
		},
	))
}