package signal_test

// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-05-29 23:12:40.765254 +0200 CEST m=+0.012581894

import (
	"testing"

	"pipelined.dev/signal"
)

func TestInt32(t *testing.T) {
	t.Run("int32", func() func(t *testing.T) {
		input := signal.Allocator{
			Channels: 3,
			Capacity: 3,
			Length:   3,
		}.Int32(signal.BitDepth32)
		signal.WriteStripedInt32(
			[][]int32{
				{},
				{1, 2, 3},
				{11, 12, 13, 14},
			},
			input,
		)
		return testOk(
			signal.Allocator{
				Channels: 3,
				Capacity: 2,
			}.Int32(signal.BitDepth32).Append(input).Slice(1, 3),
			expected{
				length:   2,
				capacity: 4,
				data: [][]int32{
					{0, 0},
					{2, 3},
					{12, 13},
				},
			},
		)
	}())
}
