// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-05-18 20:10:02.769603 +0200 CEST m=+0.007962418
package signal_test

import (
	"testing"

	"pipelined.dev/signal"
)

func TestInt8(t *testing.T) {
	t.Run("int8 append", testOk(
		signal.Allocator{
			Channels: 3,
			Capacity: 2,
		}.Int8(signal.BitDepth8).
			Append(signal.WriteStripedInt8(
				[][]int8{
					{},
					{1, 2, 3},
					{11, 12, 13, 14},
				},
				signal.Allocator{
					Channels: 3,
					Capacity: 3,
				}.Int8(signal.BitDepth8)),
			).
			Slice(1, 3),
		expected{
			length:   2,
			capacity: 4,
			data: [][]int8{
				{0, 0},
				{2, 3},
				{12, 13},
			},
		},
	))
}
