package signal_test

// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-06-01 19:53:23.337156 +0200 CEST m=+0.005857693

import (
	"testing"

	"pipelined.dev/signal"
)

func TestInt8(t *testing.T) {
	t.Run("int8", func() func(t *testing.T) {
		input := signal.Allocator{
			Channels: 3,
			Capacity: 3,
			Length:   3,
		}.Int8(signal.BitDepth8)
		signal.WriteStripedInt8(
			[][]int8{
				{},
				{1, 2, 3},
				{11, 12, 13, 14},
			},
			input,
		)
		return testOk(
			signal.Allocator{
				Channels: 3,
				Capacity: 2,
			}.Int8(signal.BitDepth8).Append(input).Slice(1, 3),
			expected{
				length:   2,
				capacity: 4,
				data: [][]int8{
					{0, 0},
					{2, 3},
					{12, 13},
				},
			},
		)
	}())
}
