// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-05-18 20:18:05.388714 +0200 CEST m=+0.015301638
package signal_test

import (
	"testing"

	"pipelined.dev/signal"
)

func TestUint8(t *testing.T) {
	t.Run("uint8", testOk(
		signal.Allocator{
			Channels: 3,
			Capacity: 2,
		}.Uint8(signal.BitDepth8).
			Append(signal.WriteStripedUint8(
				[][]uint8{
					{},
					{1, 2, 3},
					{11, 12, 13, 14},
				},
				signal.Allocator{
					Channels: 3,
					Capacity: 3,
				}.Uint8(signal.BitDepth8)),
			).
			Slice(1, 3),
		expected{
			length:   2,
			capacity: 4,
			data: [][]uint8{
				{0, 0},
				{2, 3},
				{12, 13},
			},
		},
	))
}