package signal_test

// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-09-15 08:30:21.244979 +0200 CEST m=+0.009266799

import (
	"testing"

	"pipelined.dev/signal"
)

func TestUint64(t *testing.T) {
	t.Run("uint64", func() func(t *testing.T) {
		input := signal.Allocator{
			Channels: 3,
			Capacity: 3,
			Length:   3,
		}.Uint64(signal.BitDepth64)
		signal.WriteStripedUint64(
			[][]uint64{
				{},
				{1, 2, 3},
				{11, 12, 13, 14},
			},
			input,
		)
		result := signal.Allocator{
				Channels: 3,
				Capacity: 2,
			}.Uint64(signal.BitDepth64)
		result.Append(input.Slice(1, 3))
		return testOk(
			result,
			expected{
				length:   2,
				capacity: 2,
				data: [][]uint64{
					{0, 0},
					{2, 3},
					{12, 13},
				},
			},
		)
	}())
}
